[package]
name = "pork"
version = "0.1.0"
edition = "2024"
authors = ["Lewin Probst <info@emirror.de>"]

[workspace]
members = ["pork-proto"]

[dependencies]
interprocess = { version = "2.4.0", features = ["async"] }
ipc-channel = { version = "0.21.0", features = ["async"] }
nix = { version = "0.29.0", features = ["signal"] }
pork-proto = { path = "pork-proto", features = ["codec-json", "codec-postcard"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.50.0", features = ["full"] }
