[package]
name = "pork-proto"
version = "0.1.0"
edition = "2024"
authors = ["Lewin Probst <info@emirror.de>"]
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/emirror-de/pork"

[lints]
workspace = true

[features]
default = []
codec-json = ["dep:serde_json"]
codec-postcard = ["dep:postcard"]

[dependencies]
postcard = { version = "1.1.3", optional = true, features = ["use-std"] }
serde.workspace = true
serde_json = { version = "1.0.149", optional = true }
