[package]
name = "pork-proto"
version = "0.1.0"
edition = "2024"
authors = ["Lewin Probst <info@emirror.de>"]

[features]
default = []
codec-json = ["dep:serde_json"]
codec-postcard = ["dep:postcard"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", optional = true }
postcard = { version = "1.1", features = ["alloc"], optional = true }
