[package]
name = "pork"
version = "1.0.0"
edition = "2024"
authors = ["Lewin Probst <info@emirror.de>"]
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/emirror-de/pork"
description = "Host/child process orchestration with IPC bootstrap and graceful shutdown"

[features]
default = []
codec-json = []
codec-postcard = []

[dependencies]
futures-util = "0.3"
interprocess.workspace = true
ipc-channel.workspace = true
nix.workspace = true
pork-proto = { version = "1", path = "../pork-proto", features = ["codec-json", "codec-postcard"] }
serde.workspace = true
tokio.workspace = true

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
